server:
  host: "0.0.0.0"
  port: 8080
  mode: "release"

logger:
  level: "warn"
  format: "json"
  output: "file"
  file_path: "logs/app.log"
  max_size: 100
  max_backups: 5
  max_age: 30

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: ""
  dbname: "nova"
  charset: "utf8"
  max_idle: 10
  max_open: 100
